apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-index-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-index-volume
          configMap:
            name: nginx-index-html
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: debug
  name: debug
spec:
  containers:
  - image: thihathura/test-container
    name: debug
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}